<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-NotificacoesWorker-ae69d797-49f5-41e7-8b85-16387fad8aa7</UserSecretsId>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AWSSDK.SQS" Version="4.0.2.2" />
        <PackageReference Include="MailKit" Version="4.14.1" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.10" />
    </ItemGroup>
</Project>
